# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\wdAsst\ChangeStandardLexicon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_standard_lexicon(object):
    def setupUi(self, change_standard_lexicon):
        change_standard_lexicon.setObjectName("change_standard_lexicon")
        change_standard_lexicon.resize(360, 170)
        change_standard_lexicon.setMinimumSize(QtCore.QSize(360, 170))
        change_standard_lexicon.setMaximumSize(QtCore.QSize(360, 170))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        change_standard_lexicon.setFont(font)
        self.choose_lexicon = QtWidgets.QComboBox(change_standard_lexicon)
        self.choose_lexicon.setGeometry(QtCore.QRect(30, 60, 301, 31))
        self.choose_lexicon.setObjectName("choose_lexicon")
        self.ok_btn = QtWidgets.QPushButton(change_standard_lexicon)
        self.ok_btn.setGeometry(QtCore.QRect(30, 110, 151, 31))
        self.ok_btn.setObjectName("ok_btn")
        self.cancel_btn = QtWidgets.QPushButton(change_standard_lexicon)
        self.cancel_btn.setGeometry(QtCore.QRect(190, 110, 141, 31))
        self.cancel_btn.setObjectName("cancel_btn")
        self.label = QtWidgets.QLabel(change_standard_lexicon)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(change_standard_lexicon)
        QtCore.QMetaObject.connectSlotsByName(change_standard_lexicon)

    def retranslateUi(self, change_standard_lexicon):
        _translate = QtCore.QCoreApplication.translate
        change_standard_lexicon.setWindowTitle(_translate("change_standard_lexicon", "更改标准词库"))
        self.ok_btn.setText(_translate("change_standard_lexicon", "确定"))
        self.cancel_btn.setText(_translate("change_standard_lexicon", "取消"))
        self.label.setText(_translate("change_standard_lexicon", "选择标准词库"))
