# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfirmAddWord.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmAddWord(object):
    def setupUi(self, ConfirmAddWord):
        ConfirmAddWord.setObjectName("ConfirmAddWord")
        ConfirmAddWord.resize(380, 250)
        ConfirmAddWord.setMinimumSize(QtCore.QSize(380, 250))
        ConfirmAddWord.setMaximumSize(QtCore.QSize(380, 250))
        self.trans_box = QtWidgets.QListWidget(ConfirmAddWord)
        self.trans_box.setGeometry(QtCore.QRect(19, 60, 341, 141))
        self.trans_box.setWordWrap(True)
        self.trans_box.setObjectName("trans_box")
        self.eng_label = QtWidgets.QTextEdit(ConfirmAddWord)
        self.eng_label.setGeometry(QtCore.QRect(19, 20, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.eng_label.setFont(font)
        self.eng_label.setReadOnly(True)
        self.eng_label.setObjectName("eng_label")
        self.widget = QtWidgets.QWidget(ConfirmAddWord)
        self.widget.setGeometry(QtCore.QRect(200, 210, 158, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_btn = QtWidgets.QPushButton(self.widget)
        self.ok_btn.setObjectName("ok_btn")
        self.operate_btn = QtWidgets.QButtonGroup(ConfirmAddWord)
        self.operate_btn.setObjectName("operate_btn")
        self.operate_btn.addButton(self.ok_btn)
        self.horizontalLayout.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.widget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.operate_btn.addButton(self.cancel_btn)
        self.horizontalLayout.addWidget(self.cancel_btn)

        self.retranslateUi(ConfirmAddWord)
        QtCore.QMetaObject.connectSlotsByName(ConfirmAddWord)

    def retranslateUi(self, ConfirmAddWord):
        _translate = QtCore.QCoreApplication.translate
        ConfirmAddWord.setWindowTitle(_translate("ConfirmAddWord", "确认添加的单词信息"))
        self.ok_btn.setText(_translate("ConfirmAddWord", "添加"))
        self.cancel_btn.setText(_translate("ConfirmAddWord", "取消"))
