# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManageGroupRename.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageGroupRename(object):
    def setupUi(self, ManageGroupRename):
        ManageGroupRename.setObjectName("ManageGroupRename")
        ManageGroupRename.resize(400, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ManageGroupRename.sizePolicy().hasHeightForWidth())
        ManageGroupRename.setSizePolicy(sizePolicy)
        ManageGroupRename.setMinimumSize(QtCore.QSize(400, 150))
        ManageGroupRename.setMaximumSize(QtCore.QSize(400, 150))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        ManageGroupRename.setFont(font)
        self.originName = QtWidgets.QLineEdit(ManageGroupRename)
        self.originName.setGeometry(QtCore.QRect(80, 15, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.originName.setFont(font)
        self.originName.setText("")
        self.originName.setReadOnly(True)
        self.originName.setObjectName("originName")
        self.newLabel = QtWidgets.QLabel(ManageGroupRename)
        self.newLabel.setGeometry(QtCore.QRect(20, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.newLabel.setFont(font)
        self.newLabel.setObjectName("newLabel")
        self.originLabel = QtWidgets.QLabel(ManageGroupRename)
        self.originLabel.setGeometry(QtCore.QRect(20, 65, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.originLabel.setFont(font)
        self.originLabel.setObjectName("originLabel")
        self.newName = QtWidgets.QLineEdit(ManageGroupRename)
        self.newName.setGeometry(QtCore.QRect(80, 60, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.newName.setFont(font)
        self.newName.setText("")
        self.newName.setReadOnly(False)
        self.newName.setObjectName("newName")
        self.widget = QtWidgets.QWidget(ManageGroupRename)
        self.widget.setGeometry(QtCore.QRect(20, 100, 361, 43))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.renameButton = QtWidgets.QPushButton(self.widget)
        self.renameButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.renameButton.setFont(font)
        self.renameButton.setStyleSheet("QPushButton{\n"
"    padding: 5px 0\n"
"}")
        self.renameButton.setObjectName("renameButton")
        self.gridLayout.addWidget(self.renameButton, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.widget)
        self.cancelButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton{\n"
"    padding: 5px 0\n"
"}")
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 0, 1, 1, 1)

        self.retranslateUi(ManageGroupRename)
        QtCore.QMetaObject.connectSlotsByName(ManageGroupRename)

    def retranslateUi(self, ManageGroupRename):
        _translate = QtCore.QCoreApplication.translate
        ManageGroupRename.setWindowTitle(_translate("ManageGroupRename", "重命名词库"))
        self.newLabel.setText(_translate("ManageGroupRename", "词库原名"))
        self.originLabel.setText(_translate("ManageGroupRename", "重新命名"))
        self.renameButton.setText(_translate("ManageGroupRename", "重命名"))
        self.cancelButton.setText(_translate("ManageGroupRename", "取消"))
